"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Settings = { domesticShippingKrw:string; buyingAgencyFeeKrw:string; exchangeRateKrwPerUsd:string; targetMarginRate:string; ebayFeeRate:string; advertisingRate:string; minimumSalePriceUsd:string|null };
export function PricingSettingsForm({ initial }: { initial: Settings|null }) {
  const router=useRouter();
  const [values,setValues]=useState({domesticShippingKrw:initial?.domesticShippingKrw??"0",buyingAgencyFeeKrw:initial?.buyingAgencyFeeKrw??"0",exchangeRateKrwPerUsd:initial?.exchangeRateKrwPerUsd??"",targetMarginPercent:initial?String(Number(initial.targetMarginRate)*100):"",ebayFeePercent:initial?String(Number(initial.ebayFeeRate)*100):"",advertisingPercent:initial?String(Number(initial.advertisingRate)*100):"",minimumSalePriceUsd:initial?.minimumSalePriceUsd??""});
  const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const [rateMessage,setRateMessage]=useState(""); const [rateLoading,setRateLoading]=useState(false);
  const set=(key:keyof typeof values,value:string)=>setValues(current=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");const response=await fetch("/api/pricing/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({domesticShippingKrw:values.domesticShippingKrw,buyingAgencyFeeKrw:values.buyingAgencyFeeKrw,exchangeRateKrwPerUsd:values.exchangeRateKrwPerUsd,targetMarginRate:String(Number(values.targetMarginPercent)/100),ebayFeeRate:String(Number(values.ebayFeePercent)/100),advertisingRate:String(Number(values.advertisingPercent)/100),minimumSalePriceUsd:values.minimumSalePriceUsd})});const body=await response.json();if(!response.ok){setMessage(body.error??"저장하지 못했습니다.");setSaving(false);return}setMessage("설정을 저장했습니다. 포카마켓 가격이 있는 상품은 다음 채널 등록·가격 반영 때 이 마진 공식으로 자동 계산됩니다.");setSaving(false);router.refresh()}
  async function fetchLatestRate(){setRateLoading(true);setRateMessage("");try{const response=await fetch("/api/pricing/exchange-rate",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"최신 환율을 가져오지 못했습니다.");set("exchangeRateKrwPerUsd",String(body.rate));setRateMessage(`${body.effectiveDate} ECB 기준 · 1 USD = ${Number(body.rate).toLocaleString()} KRW`)}catch(error){setRateMessage(error instanceof Error?error.message:"최신 환율을 가져오지 못했습니다.")}finally{setRateLoading(false)}}
  const fields:Array<[keyof typeof values,string,string]>=[["domesticShippingKrw","국내 배송비 · 카드당 실제 부담액 (KRW)","0"],["buyingAgencyFeeKrw","포카마켓 출고비 · 카드당 실제 부담액 (KRW)","0"],["exchangeRateKrwPerUsd","계산에 적용할 원·달러 환율 (KRW/USD)",""],["targetMarginPercent","사업 목표 마진율 (%)",""],["ebayFeePercent","eBay 최종가치수수료 (%)","13.25"],["advertisingPercent","General 광고율 (%) · 미사용 시 0","0"],["minimumSalePriceUsd","공통 최소 판매가 (USD) · 비워두면 미사용",""]];
  return <form onSubmit={submit} className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2">{fields.map(([key,label,placeholder])=><label key={key} className="text-sm font-medium text-zinc-700">{label}<input required={key!=="minimumSalePriceUsd"} type="number" min="0" step="any" value={values[key]} placeholder={placeholder} onChange={event=>set(key,event.target.value)} className="mt-2 w-full rounded-xl border border-zinc-300 px-3 py-2.5 outline-none focus:border-violet-500"/>{key==="exchangeRateKrwPerUsd"&&<span className="mt-2 flex items-center gap-3"><button type="button" disabled={rateLoading} onClick={fetchLatestRate} className="rounded-lg border border-violet-300 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700 disabled:opacity-50">{rateLoading?"조회 중…":"최신 환율 가져오기"}</button>{rateMessage&&<span className="text-xs font-normal text-zinc-500">{rateMessage}</span>}</span>}</label>)}</div><div className="mt-5 space-y-2 rounded-xl bg-zinc-50 p-4 text-sm text-zinc-600"><p>포카마켓 가격이 있으면 아래 설정으로 USD 판매가를 자동 계산합니다. 포카마켓 가격이 없으면 직접 입력한 USD 판매가를 사용합니다.</p><p>해외 배송비는 판매가 마진 계산에 넣지 않으며 eBay·Shopify 배송 정책에서 별도로 청구합니다.</p><p><a className="text-violet-700 underline" href="https://frankfurter.dev/" target="_blank" rel="noreferrer">환율 데이터 안내</a> · <a className="text-violet-700 underline" href="https://www.ebay.com/help/selling/fees-credits-invoices/selling-fees?id=4822" target="_blank" rel="noreferrer">eBay 공식 판매 수수료</a></p></div><div className="mt-5 flex items-center gap-3"><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"저장 중…":"가격 계산 설정 저장"}</button>{message&&<p role="status" className="text-sm">{message}</p>}</div></form>
}
