"use client";
/* eslint-disable @next/next/no-img-element */
import { useRouter } from "next/navigation";
import { useState } from "react";

type Worker={id:string;loginId:string;name:string|null;assigned:number;submitted:number;approved:number;rejected:number};
type Product={id:string;sku:string;productName:string;optionName:string|null;brand:string|null;category:string|null;imageUrl:string|null;assignmentStatus:string|null;workerId:string|null;workerName:string|null};
type Filters={q:string;group:string;album:string;member:string;state:string;sort:string};
export function ImageWorkerAdmin({workers,products,facets,pagination,filters}:{workers:Worker[];products:Product[];facets:{groups:string[];albums:string[];members:string[]};pagination:{page:number;pageSize:number;total:number;totalPages:number};filters:Filters}){
 const router=useRouter(); const [workerId,setWorkerId]=useState(workers[0]?.id??""); const [selected,setSelected]=useState<string[]>([]); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const allPage=products.length>0&&products.every(p=>selected.includes(p.id));
 const pageNumbers=Array.from({length:Math.min(5,pagination.totalPages)},(_,i)=>Math.max(1,Math.min(pagination.totalPages-4,pagination.page-2))+i).filter((n,i,a)=>n>=1&&n<=pagination.totalPages&&a.indexOf(n)===i);
 function navigate(changes:Partial<Filters>&{page?:number;pageSize?:number}){const next={...filters,...changes};const qs=new URLSearchParams();Object.entries(next).forEach(([k,v])=>{if(v)qs.set(k,String(v));});qs.set("page",String(changes.page??1));qs.set("pageSize",String(changes.pageSize??pagination.pageSize));router.push(`/image-workers?${qs}`);}
 async function createWorker(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const response=await fetch("/api/image-workers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const data=await response.json() as {error?:string};if(!response.ok)return setMessage(data.error??"계정 생성 실패");router.refresh();}
 async function assign(){if(!workerId||!selected.length)return setMessage("작업자와 상품을 선택해 주세요.");setLoading(true);const response=await fetch("/api/image-workers",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({workerId,productIds:selected})});const data=await response.json() as {error?:string;assigned?:number};setLoading(false);if(!response.ok)return setMessage(data.error??"배정 실패");setMessage(`${data.assigned??selected.length}개 상품을 배정했습니다.`);setSelected([]);router.refresh();}
 const stateLabel=(s:string|null)=>s==="assigned"?"작업 대기":s==="in_progress"?"작업 중":s==="submitted"?"검수 대기":s==="approved"?"승인":s==="rejected"?"반려":"미배정";
 return <div className="space-y-6">
  <section className="rounded-lg border bg-white p-5"><h2 className="font-semibold">작업자 현황</h2><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{workers.map(w=><div key={w.id} className="rounded border p-3"><strong>{w.name??w.loginId}</strong><p className="text-xs text-zinc-500">{w.loginId}</p><div className="mt-2 grid grid-cols-4 gap-1 text-center text-xs"><span className="rounded bg-amber-50 p-1">대기<br/><b>{w.assigned}</b></span><span className="rounded bg-blue-50 p-1">제출<br/><b>{w.submitted}</b></span><span className="rounded bg-emerald-50 p-1">승인<br/><b>{w.approved}</b></span><span className="rounded bg-rose-50 p-1">반려<br/><b>{w.rejected}</b></span></div></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">새 작업자 계정 만들기</summary><form onSubmit={createWorker} className="mt-3 grid gap-2 md:grid-cols-4"><input name="loginId" required minLength={3} placeholder="로그인 ID" className="rounded border px-3 py-2"/><input name="name" required placeholder="작업자 이름" className="rounded border px-3 py-2"/><input name="password" type="password" required minLength={6} placeholder="비밀번호 6자 이상" className="rounded border px-3 py-2"/><button className="rounded bg-zinc-950 px-4 py-2 font-semibold text-white">계정 생성</button></form></details></section>
  <section className="rounded-lg border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">이미지 작업 배정</h2><p className="text-sm text-zinc-500">검색 결과 {pagination.total.toLocaleString()}개 · {pagination.page}/{pagination.totalPages}페이지</p></div><div className="flex gap-2"><select value={workerId} onChange={e=>setWorkerId(e.target.value)} className="rounded border px-3 py-2"><option value="">작업자 선택</option>{workers.map(w=><option key={w.id} value={w.id}>{w.name??w.loginId}</option>)}</select><button onClick={assign} disabled={loading||!selected.length} className="rounded bg-violet-700 px-4 py-2 font-semibold text-white disabled:opacity-40">{loading?"배정 중":`선택 ${selected.length}개 배정/재배정`}</button></div></div>
   <form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);navigate({q:String(fd.get("q")??"")});}} className="mt-4 grid gap-2 md:grid-cols-3 xl:grid-cols-7"><input name="q" defaultValue={filters.q} placeholder="SKU 또는 상품명 검색" className="rounded border px-3 py-2 xl:col-span-2"/><select value={filters.group} onChange={e=>navigate({group:e.target.value})} className="rounded border px-2"><option value="">전체 그룹</option>{facets.groups.map(v=><option key={v}>{v}</option>)}</select><select value={filters.album} onChange={e=>navigate({album:e.target.value})} className="rounded border px-2"><option value="">전체 앨범</option>{facets.albums.map(v=><option key={v}>{v}</option>)}</select><select value={filters.member} onChange={e=>navigate({member:e.target.value})} className="rounded border px-2"><option value="">전체 멤버</option>{facets.members.map(v=><option key={v}>{v}</option>)}</select><select value={filters.state} onChange={e=>navigate({state:e.target.value})} className="rounded border px-2"><option value="unassigned">미배정</option><option value="assigned">작업 대기</option><option value="submitted">검수 대기</option><option value="approved">승인</option><option value="rejected">반려</option><option value="all">전체</option></select><button className="rounded bg-zinc-900 px-3 py-2 font-semibold text-white">검색</button></form>
   <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={allPage} onChange={e=>setSelected(e.target.checked?products.map(p=>p.id):[])}/>현재 페이지 전체 선택 ({products.length}개)</label><div className="flex gap-2"><select value={filters.sort} onChange={e=>navigate({sort:e.target.value})} className="rounded border px-2 py-1"><option value="sku">SKU순</option><option value="name">상품명순</option><option value="newest">최근 수정순</option></select><select value={pagination.pageSize} onChange={e=>navigate({pageSize:Number(e.target.value)})} className="rounded border px-2 py-1">{[50,100,200,500,1000].map(n=><option key={n} value={n}>{n}개씩 보기</option>)}</select><button onClick={()=>navigate({q:"",group:"",album:"",member:"",state:"unassigned",sort:"sku"})} className="rounded border px-3">필터 초기화</button></div></div>
   <div className="mt-3 max-h-[65vh] overflow-auto rounded border"><table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-zinc-100"><tr><th className="p-2"></th><th className="p-2 text-left">이미지</th><th className="p-2 text-left">SKU/상품명</th><th className="p-2 text-left">그룹</th><th className="p-2 text-left">앨범</th><th className="p-2 text-left">멤버</th><th className="p-2 text-left">상태</th><th className="p-2 text-left">작업자</th></tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t hover:bg-zinc-50"><td className="p-2"><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/></td><td className="p-2">{p.imageUrl?<img src={p.imageUrl} alt="" className="h-16 w-12 rounded object-contain"/>:null}</td><td className="p-2"><b>{p.sku}</b><div className="max-w-md truncate text-zinc-500">{p.productName}</div></td><td className="p-2">{p.brand??"-"}</td><td className="p-2">{p.category??"-"}</td><td className="p-2">{p.optionName??"-"}</td><td className="p-2"><span className="rounded-full bg-zinc-100 px-2 py-1 text-xs font-semibold">{stateLabel(p.assignmentStatus)}</span></td><td className="p-2">{p.workerName??"-"}</td></tr>)}</tbody></table>{!products.length?<div className="p-10 text-center text-zinc-500">조건에 맞는 상품이 없습니다.</div>:null}</div>
   <div className="mt-4 flex flex-wrap items-center justify-center gap-2"><button disabled={pagination.page<=1} onClick={()=>navigate({page:1})} className="rounded border px-3 py-2 disabled:opacity-30">처음</button><button disabled={pagination.page<=1} onClick={()=>navigate({page:pagination.page-1})} className="rounded border px-3 py-2 disabled:opacity-30">이전</button>{pageNumbers.map(n=><button key={n} onClick={()=>navigate({page:n})} className={`h-9 min-w-9 rounded border px-2 ${n===pagination.page?"bg-zinc-950 text-white":"bg-white"}`}>{n}</button>)}<button disabled={pagination.page>=pagination.totalPages} onClick={()=>navigate({page:pagination.page+1})} className="rounded border px-3 py-2 disabled:opacity-30">다음</button><button disabled={pagination.page>=pagination.totalPages} onClick={()=>navigate({page:pagination.totalPages})} className="rounded border px-3 py-2 disabled:opacity-30">마지막</button></div>{message?<p className="mt-3 text-sm font-semibold text-violet-700">{message}</p>:null}
  </section>
 </div>;
}
