"use client";

import { useEffect, useState } from "react";

export function ListingWatermarkControls() {
  const [text, setText] = useState(""); const [opacity, setOpacity] = useState(.06); const [size, setSize] = useState(50); const [gap, setGap] = useState(25); const [individual, setIndividual] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/listing-upload/variation-thumbnail/logo").then((r) => r.json()).then((data) => { setText(data.watermarkText ?? ""); setOpacity(Number(data.watermarkOpacity ?? .06)); setSize(Number(data.watermarkLogoSize ?? 50)); setGap(Number(data.watermarkGap ?? 25)); setIndividual(data.applyToIndividualCards ?? true); }).catch(() => setMessage("저장된 워터마크 설정을 불러오지 못했습니다.")); }, []);
  async function save() { setSaving(true); setMessage(""); try { const response = await fetch("/api/listing-upload/variation-thumbnail/logo", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ watermarkText: text.trim() || null, watermarkOpacity: opacity, watermarkLogoSize: size, watermarkGap: gap, applyToIndividualCards: individual }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "저장 실패"); setMessage("저장했습니다. 기존 Shopify 상품은 ‘변동·품단종 관리 → 이미지·썸네일 교체’에서 전송하면 새 설정으로 교체됩니다."); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } }
  return <section className="mb-5 rounded-2xl border border-violet-200 bg-violet-50 p-4"><h2 className="font-bold text-violet-950">판매용 워터마크 설정</h2><p className="mt-1 text-xs text-violet-900">로고는 아래 묶음 썸네일 생성 화면에서 PNG로 저장합니다. 이 값은 묶음 대표 썸네일과 Shopify 개별 카드 판매 사진에 함께 적용됩니다. 원본 이미지는 바꾸지 않습니다.</p><div className="mt-3 grid gap-3 md:grid-cols-4"><label className="text-xs font-medium">문구(로고 없을 때)<input value={text} onChange={(e) => setText(e.target.value)} maxLength={80} className="mt-1 h-10 w-full rounded border bg-white px-2 text-sm" placeholder="쇼핑몰 이름" /></label><label className="text-xs font-medium">투명도 {Math.round(opacity * 100)}%<input type="range" min=".03" max=".3" step=".01" value={opacity} onChange={(e) => setOpacity(Number(e.target.value))} className="mt-3 w-full" /></label><label className="text-xs font-medium">반복 크기 {size}px<input type="range" min="35" max="220" step="5" value={size} onChange={(e) => setSize(Number(e.target.value))} className="mt-3 w-full" /></label><label className="text-xs font-medium">반복 간격 {gap}px<input type="range" min="10" max="180" step="5" value={gap} onChange={(e) => setGap(Number(e.target.value))} className="mt-3 w-full" /></label></div><label className="mt-3 flex items-center gap-2 text-sm font-medium text-violet-950"><input type="checkbox" checked={individual} onChange={(e) => setIndividual(e.target.checked)} />개별 카드 사진에도 워터마크 적용</label><div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" disabled={saving} onClick={() => void save()} className="rounded-lg bg-violet-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "저장 중…" : "자동 적용 설정 저장"}</button>{message && <p className="text-xs text-violet-900">{message}</p>}</div></section>;
}
