"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Product={id:string;sku:string;productName:string;salePrice:string|null};
type Item={id:string;productId:string;pocaPriceKrw:string;totalCostKrw:string;costUsd:string;rawRecommendedPriceUsd:string;recommendedPriceUsd:string;expectedProceedsUsd:string;expectedNetMarginUsd:string;expectedNetMarginRate:string;appliedDraftId:string|null;product:{sku:string;productName:string}};
type Review={id:string;status:string;createdAt:string;approvedAt:string|null;items:Item[]};
type Draft={id:string;sourceInventoryId:string|null;sku:string;title:string;price:string|null};
export function PricingReviewClient({products,initialReviews,drafts}:{products:Product[];initialReviews:Review[];drafts:Draft[]}){
 const router=useRouter();const [selected,setSelected]=useState<string[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [draftChoice,setDraftChoice]=useState<Record<string,string>>({});
 async function action(url:string,payload:object,success:string){setBusy(true);setMessage("");const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();setMessage(response.ok?success:body.error??"처리하지 못했습니다.");setBusy(false);if(response.ok)router.refresh()}
 return <div className="space-y-7"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">계산할 상품 선택</h2><p className="text-sm text-zinc-500">계산 결과는 검토 레코드로만 저장됩니다.</p></div><button disabled={busy||!selected.length} onClick={()=>action("/api/pricing/reviews",{productIds:selected},"권장가를 계산했습니다. 아직 가격에는 반영되지 않았습니다.")} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">선택 상품 계산</button></div><div className="max-h-72 overflow-auto rounded-xl border">{products.map(product=><label key={product.id} className="flex items-center gap-3 border-b px-4 py-3 text-sm last:border-0"><input type="checkbox" checked={selected.includes(product.id)} disabled={!product.salePrice} onChange={event=>setSelected(current=>event.target.checked?[...current,product.id]:current.filter(id=>id!==product.id))}/><span className="w-32 font-mono">{product.sku}</span><span className="min-w-0 flex-1 truncate">{product.productName}</span><span>{product.salePrice?`${Number(product.salePrice).toLocaleString()}원`:"포카마켓 가격 없음"}</span></label>)}</div></section>
 {message&&<p role="status" className="rounded-xl bg-violet-50 p-4 text-sm text-violet-800">{message}</p>}
 {initialReviews.map(review=><section key={review.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">검토 {review.id.slice(-8)}</h2><p className="text-sm text-zinc-500">{new Date(review.createdAt).toLocaleString()} · {review.status}</p></div>{review.status==="DRAFT"&&<button disabled={busy} onClick={()=>action(`/api/pricing/reviews/${review.id}/approve`,{confirmed:true},"승인했습니다. 아직 업로드 가격에는 반영되지 않았습니다.")} className="rounded-xl border border-violet-600 px-4 py-2 text-sm font-semibold text-violet-700">검토 후 승인</button>}</div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr>{["상품","포카 가격","총 원가","USD 원가","계산가","최종 권장가","예상 정산액","예상 순수마진","업로드 초안 적용"].map(label=><th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{review.items.map(item=>{const choices=drafts.filter(draft=>draft.sourceInventoryId===item.productId);return <tr key={item.id} className="border-t"><td className="px-3 py-3"><b>{item.product.sku}</b><br/><span className="text-zinc-500">{item.product.productName}</span></td><td className="px-3">{Number(item.pocaPriceKrw).toLocaleString()}원</td><td className="px-3">{Number(item.totalCostKrw).toLocaleString()}원</td><td className="px-3">${Number(item.costUsd).toFixed(2)}</td><td className="px-3">${Number(item.rawRecommendedPriceUsd).toFixed(4)}</td><td className="px-3 font-semibold">${Number(item.recommendedPriceUsd).toFixed(2)}</td><td className="px-3">${Number(item.expectedProceedsUsd).toFixed(2)}</td><td className="px-3">${Number(item.expectedNetMarginUsd).toFixed(2)}<br/><span className="text-zinc-500">{(Number(item.expectedNetMarginRate)*100).toFixed(1)}%</span></td><td className="px-3">{item.appliedDraftId?<span className="text-emerald-700">적용 완료</span>:review.status!=="APPROVED"?<span className="text-zinc-400">승인 필요</span>:choices.length?<div className="flex gap-2"><select value={draftChoice[item.id]??""} onChange={event=>setDraftChoice(current=>({...current,[item.id]:event.target.value}))} className="max-w-40 rounded-lg border px-2 py-1.5"><option value="">초안 선택</option>{choices.map(draft=><option key={draft.id} value={draft.id}>{draft.sku} · {draft.title}</option>)}</select><button disabled={!draftChoice[item.id]||busy} onClick={()=>action(`/api/pricing/reviews/items/${item.id}/apply`,{confirmed:true,draftId:draftChoice[item.id]},"승인된 권장가를 업로드 초안에 적용했습니다.")} className="rounded-lg bg-zinc-900 px-3 py-1.5 text-white disabled:opacity-40">적용</button></div>:<span className="text-amber-700">상품 업로드 초안 없음</span>}</td></tr>})}</tbody></table></div></section>)}</div>
}
