"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Settings = { domesticShippingKrw:string; buyingAgencyFeeKrw:string; exchangeRateKrwPerUsd:string; targetMarginRate:string; ebayFeeRate:string; advertisingRate:string };
export function PricingSettingsForm({ initial, calculationProductIds }: { initial: Settings|null; calculationProductIds:string[] }) {
  const router=useRouter();
  const [values,setValues]=useState({domesticShippingKrw:initial?.domesticShippingKrw??"0",buyingAgencyFeeKrw:initial?.buyingAgencyFeeKrw??"0",exchangeRateKrwPerUsd:initial?.exchangeRateKrwPerUsd??"",targetMarginPercent:initial?String(Number(initial.targetMarginRate)*100):"",ebayFeePercent:initial?String(Number(initial.ebayFeeRate)*100):"",advertisingPercent:initial?String(Number(initial.advertisingRate)*100):""});
  const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
  const [rateMessage,setRateMessage]=useState(""); const [rateLoading,setRateLoading]=useState(false);
  const set=(key:keyof typeof values,value:string)=>setValues(current=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");const response=await fetch("/api/pricing/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({domesticShippingKrw:values.domesticShippingKrw,buyingAgencyFeeKrw:values.buyingAgencyFeeKrw,exchangeRateKrwPerUsd:values.exchangeRateKrwPerUsd,targetMarginRate:String(Number(values.targetMarginPercent)/100),ebayFeeRate:String(Number(values.ebayFeePercent)/100),advertisingRate:String(Number(values.advertisingPercent)/100)})});const body=await response.json();if(!response.ok){setMessage(body.error??"저장하지 못했습니다.");setSaving(false);return}if(calculationProductIds.length){const calculation=await fetch("/api/pricing/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productIds:calculationProductIds})});const result=await calculation.json();setMessage(calculation.ok?`설정을 저장하고 가격이 있는 상품 ${calculationProductIds.length}개의 권장가를 계산했습니다.`:result.error??"설정은 저장했지만 계산하지 못했습니다.")}else setMessage("설정을 저장했습니다. 계산 가능한 포카마켓 가격 상품이 없습니다.");setSaving(false);router.refresh()}
  async function fetchLatestRate(){setRateLoading(true);setRateMessage("");try{const response=await fetch("/api/pricing/exchange-rate",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"최신 환율을 가져오지 못했습니다.");set("exchangeRateKrwPerUsd",String(body.rate));setRateMessage(`${body.effectiveDate} ECB 기준 · 1 USD = ${Number(body.rate).toLocaleString()} KRW`)}catch(error){setRateMessage(error instanceof Error?error.message:"최신 환율을 가져오지 못했습니다.")}finally{setRateLoading(false)}}
  const fields:Array<[keyof typeof values,string,string]>=[["domesticShippingKrw","국내 배송비 · 카드당 실제 부담액 (KRW)","0"],["buyingAgencyFeeKrw","포카마켓 출고비 · 카드당 실제 부담액 (KRW)","0"],["exchangeRateKrwPerUsd","계산에 적용할 원·달러 환율 (KRW/USD)",""],["targetMarginPercent","사업 목표 마진율 (%)",""],["ebayFeePercent","eBay 최종가치수수료 (%)","13.25"],["advertisingPercent","General 광고율 (%) · 미사용 시 0","0"]];
  return <form onSubmit={submit} className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2">{fields.map(([key,label,placeholder])=><label key={key} className="text-sm font-medium text-zinc-700">{label}<input required type="number" min="0" step="any" value={values[key]} placeholder={placeholder} onChange={event=>set(key,event.target.value)} className="mt-2 w-full rounded-xl border border-zinc-300 px-3 py-2.5 outline-none focus:border-violet-500"/>{key==="exchangeRateKrwPerUsd"&&<span className="mt-2 flex items-center gap-3"><button type="button" disabled={rateLoading} onClick={fetchLatestRate} className="rounded-lg border border-violet-300 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-700 disabled:opacity-50">{rateLoading?"조회 중…":"최신 환율 가져오기"}</button>{rateMessage&&<span className="text-xs font-normal text-zinc-500">{rateMessage}</span>}</span>}</label>)}</div><div className="mt-5 space-y-2 rounded-xl bg-zinc-50 p-4 text-sm text-zinc-600"><p>최신 환율은 ECB 공식 일일 기준환율을 Frankfurter API로 조회합니다. 휴일에는 가장 최근 영업일 값이 표시되며, 조회만으로 설정이 저장되지는 않습니다.</p><p>Non-Sport Trading Cards 공식 수수료: Store 미구독 13.25%, Basic 이상 Store 12.35% (구간 한도 이하). 계정 구독 상태에 맞게 입력하세요.</p><p>General 광고율은 고정 정답이 없으며 eBay가 상품별로 매일 제안합니다. 광고 미사용은 0%, 사용할 경우 공식 허용 범위는 2~100%입니다.</p><p>eBay 주문당 고정 수수료($10 이하 $0.30, 초과 $0.40)는 승인된 계산 공식에 포함되지 않습니다. 다음 $0.10로 올림하며 해외 배송비와 환율 변동 여유분도 제외합니다.</p><p><a className="text-violet-700 underline" href="https://frankfurter.dev/" target="_blank" rel="noreferrer">환율 데이터 안내</a> · <a className="text-violet-700 underline" href="https://www.ebay.com/help/selling/fees-credits-invoices/selling-fees?id=4822" target="_blank" rel="noreferrer">eBay 공식 판매 수수료</a></p></div><div className="mt-5 flex items-center gap-3"><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"저장·계산 중…":"설정 저장 후 권장가 계산"}</button>{message&&<p role="status" className="text-sm">{message}</p>}</div></form>
}
