"use client";

import { useState } from "react";

type Result = { from:string;to:string;rows:Array<{orderId:string;externalOrderId:string;channel:string;orderDate:string;grossOrderAmount:number;currency:string;actual:{net:number;fees:number;gross:number;currency:string;payoutId:string|null}|null;costUsd:number|null;actualMargin:number|null;matched:boolean}>;channels:{ebay:{error:string|null;reconnectRequired:boolean};shopify:{error:string|null;permissionRequired:boolean}} };

function money(value:number|null|undefined,currency="USD"){return value==null?"-":new Intl.NumberFormat("en-US",{style:"currency",currency}).format(value)}

export function SettlementReconciliationClient(){
  const [days,setDays]=useState(30);const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  async function load(){setBusy(true);setMessage("");const response=await fetch(`/api/settlements/reconcile?days=${days}`,{cache:"no-store"});const body=await response.json();setBusy(false);if(!response.ok){setMessage(body.error??"조회 실패");return}setResult(body)}
  return <div className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="text-sm font-semibold">조회 기간<select value={days} onChange={e=>setDays(Number(e.target.value))} className="ml-3 rounded-xl border px-3 py-2"><option value={7}>7일</option><option value={30}>30일</option><option value={90}>90일</option></select></label><button disabled={busy} onClick={()=>void load()} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?"조회 중…":"실제 정산 조회"}</button></div><p className="mt-3 text-xs text-zinc-500">읽기 전용 조회입니다. 주문번호가 정확히 일치한 정산만 연결하며 원가가 없는 주문은 마진을 계산하지 않습니다.</p>{message&&<p className="mt-3 text-sm text-rose-700">{message}</p>}</section>{result&&<><div className="grid gap-3 sm:grid-cols-2">{result.channels.ebay.error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>eBay</b> · {result.channels.ebay.reconnectRequired?"Finances 권한을 추가해 eBay를 다시 연결해야 합니다.":result.channels.ebay.error}</div>}{result.channels.shopify.error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>Shopify</b> · {result.channels.shopify.permissionRequired?"read_shopify_payments_payouts 권한을 앱에 추가해야 합니다.":result.channels.shopify.error}</div>}</div><section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-4 font-bold">주문별 대조 · 정산 연결 {result.rows.filter(r=>r.matched).length}/{result.rows.length}건</div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-zinc-50 text-zinc-500"><tr>{["주문","채널","주문액","실제 정산액","실제 수수료","계산 원가","실제 마진","지급 ID"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{result.rows.map(row=><tr key={row.orderId} className="border-t"><td className="px-3 py-3"><b>{row.externalOrderId}</b><br/><span className="text-xs text-zinc-500">{new Date(row.orderDate).toLocaleDateString("ko-KR")}</span></td><td className="px-3">{row.channel}</td><td className="px-3">{money(row.grossOrderAmount,row.currency)}</td><td className="px-3 font-semibold">{money(row.actual?.net,row.actual?.currency)}</td><td className="px-3">{money(row.actual?.fees,row.actual?.currency)}</td><td className="px-3">{money(row.costUsd)}</td><td className={`px-3 font-semibold ${row.actualMargin!=null&&row.actualMargin<0?"text-rose-700":"text-emerald-700"}`}>{money(row.actualMargin)}</td><td className="px-3 text-xs text-zinc-500">{row.actual?.payoutId??"-"}</td></tr>)}</tbody></table></div></section></>}</div>
}
