"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useState } from "react";
type Product={id:string;sku:string;variationName:string;imageUrl:string|null;priceUsd:string|null};
type Group={key:string;groupName:string;albumName:string;versionName:string;title:string;products:Product[];truncated:boolean;activeSingleCount:number;ebayItemId:string|null;includedCount:number;newOptionCount:number;thumbnailStatus:"READY"|"FAILED"|"MISSING";thumbnailUrl:string|null;thumbnailError:string|null;thumbnailGeneratedAt:string|null};
type Payload={groups:Group[];unmatchedCount:number;missingPriceCount:number;latestCompleteReportAt:string|null;pricingReady:boolean};
export function VariationListingGroupsClient(){
 const [data,setData]=useState<Payload|null>(null);const [selected,setSelected]=useState<string[]>([]);const [query,setQuery]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [preview,setPreview]=useState<{url:string;title:string}|null>(null);const [previewing,setPreviewing]=useState<string|null>(null);const [progress,setProgress]=useState<{completed:number;total:number;startedAt:number;currentTitle:string}|null>(null);const [elapsedSeconds,setElapsedSeconds]=useState(0);
 useEffect(()=>{void fetch("/api/listing-upload/variation-groups",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}).catch(e=>setError(String(e)))},[]);
 const progressStartedAt=progress?.startedAt;
 useEffect(()=>{if(!progressStartedAt)return;const timer=window.setInterval(()=>setElapsedSeconds(Math.floor((Date.now()-progressStartedAt)/1000)),1000);return()=>window.clearInterval(timer)},[progressStartedAt]);
 const shown=useMemo(()=>data?.groups.filter(g=>!query.trim()||`${g.title} ${g.products.map(p=>p.variationName).join(" ")}`.toLowerCase().includes(query.toLowerCase()))??[],[data,query]);
 const selectedGroups=useMemo(()=>data?.groups.filter(group=>selected.includes(group.key))??[],[data,selected]);
 const selectedReady=selectedGroups.length>0&&selectedGroups.every(group=>group.thumbnailStatus==="READY");
 const toggle=(key:string)=>setSelected(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);
 function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${name}-${new Date().toISOString().slice(0,10)}.csv`;a.style.display="none";document.body.appendChild(a);a.click();window.setTimeout(()=>{a.remove();URL.revokeObjectURL(url)},1000)}
 async function requestCsv(endpoint:string,groupKeys:string[]){const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),120_000);try{const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},signal:controller.signal,body:JSON.stringify({groupKeys,confirmed:true})});if(!r.ok){const contentType=r.headers.get("content-type")??"";const message=contentType.includes("application/json")?(await r.json()).error:await r.text();throw new Error(message||"파일 생성 실패")}return await r.blob()}finally{window.clearTimeout(timeout)}}
 async function download(endpoint:string,name:string){setBusy(true);setError(null);try{const blob=await requestCsv(endpoint,selected);saveBlob(blob,name)}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"처리가 2분을 넘겨 중단되었습니다. R2 연결과 상품 이미지 응답 상태를 확인해 주세요.":e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function refreshGroups(){const r=await fetch("/api/listing-upload/variation-groups",{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error||"묶음 상태를 새로고치지 못했습니다.");setData(body)}
 async function prepareThumbnails(){setBusy(true);setError(null);setElapsedSeconds(0);const startedAt=Date.now();setProgress({completed:0,total:selected.length,startedAt,currentTitle:"준비 중"});try{for(let index=0;index<selected.length;index+=1){const key=selected[index];const title=data?.groups.find(group=>group.key===key)?.title??key;setProgress({completed:index,total:selected.length,startedAt,currentTitle:title});const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),120_000);try{const r=await fetch("/api/listing-upload/variation-groups/prepare-thumbnail",{method:"POST",headers:{"content-type":"application/json"},signal:controller.signal,body:JSON.stringify({groupKey:key})});const body=await r.json();if(!r.ok)throw new Error(body.error||"썸네일 생성 실패")}finally{window.clearTimeout(timeout)}setProgress({completed:index+1,total:selected.length,startedAt,currentTitle:title})}await refreshGroups()}catch(e){await refreshGroups().catch(()=>{});setError(e instanceof DOMException&&e.name==="AbortError"?"현재 묶음의 썸네일 생성이 2분을 넘겨 중단되었습니다.":e instanceof Error?e.message:String(e))}finally{setBusy(false);window.setTimeout(()=>setProgress(null),1500)}}
 async function downloadVariationCsv(){setBusy(true);setError(null);try{const parts:string[]=[];for(let offset=0;offset<selected.length;offset+=20){const blob=await requestCsv("/api/listing-upload/variation-groups/export",selected.slice(offset,offset+20));const text=(await blob.text()).replace(/^\uFEFF/,"");parts.push(offset===0?text:text.split(/\r?\n/).slice(1).join("\r\n"))}saveBlob(new Blob([`\uFEFF${parts.filter(Boolean).join("\r\n")}`],{type:"text/csv;charset=utf-8"}),"ebay-variation-listings")}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"CSV 생성이 2분을 넘겨 중단되었습니다.":e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function showPreview(group:Group){setPreviewing(group.key);setError(null);try{const r=await fetch("/api/listing-upload/variation-groups/preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupKey:group.key})});const b=await r.json();if(!r.ok)throw new Error(b.error||"미리보기 생성 실패");setPreview({url:b.dataUrl,title:group.title})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setPreviewing(null)}}
 if(!data)return <p className="rounded-xl border bg-white p-6 text-sm text-zinc-500">{error||"묶음 후보를 분석하고 있습니다…"}</p>;
 return <div className="space-y-4">
  <section className="grid gap-3 sm:grid-cols-4"><Stat label="묶음상품 후보" value={`${data.groups.length}개`}/><Stat label="선택 옵션" value={`${data.groups.reduce((n,g)=>n+g.products.length,0)}장`}/><Stat label="단품 유지" value={`${data.unmatchedCount}장`}/><Stat label="가격 미입력" value={`${data.missingPriceCount}장`}/></section>
  <section className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><b>업로드 순서</b><p className="mt-1 text-xs leading-5">썸네일 미리보기 → 신규 등록·옵션 추가 CSV 업로드 → eBay 전체 활성상품 보고서 다시 가져오기 → 반영 확인 후 기존 단품 종료 CSV 업로드. CSV 생성 시 미리보기와 같은 구성을 R2에 업로드합니다.</p></section>
  <section className="rounded-xl border bg-white p-4"><div className="flex gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="그룹, 앨범, 버전, 멤버 검색" className="h-10 flex-1 rounded-md border px-3 text-sm"/><button onClick={()=>setSelected(shown.filter(g=>!g.truncated).map(g=>g.key))} className="text-sm font-semibold text-violet-700">전체 선택</button></div>
   <div className="mt-4 space-y-3">{shown.map(g=><article key={g.key} className={`grid gap-4 rounded-xl border p-4 md:grid-cols-[180px_1fr] ${selected.includes(g.key)?"border-violet-500 bg-violet-50":""}`}><button type="button" onClick={()=>showPreview(g)} className="overflow-hidden rounded-lg border bg-white text-left shadow-sm"><div className="px-2 py-2 text-center"><b className="block truncate text-xs">{g.groupName}</b><span className="block truncate text-[10px] text-zinc-500">{[g.albumName,g.versionName].filter(Boolean).join(" · ")}</span></div><div className="grid aspect-square grid-cols-4 gap-0.5 bg-zinc-100 p-1">{g.products.slice(0,16).map(p=>p.imageUrl?<img key={p.id} src={p.imageUrl} alt="" className="h-full min-h-0 w-full object-cover"/>:<span key={p.id}/>)}</div><span className="block p-2 text-center text-[10px] font-semibold text-violet-700">{previewing===g.key?"정확한 원본 생성 중…":"눌러서 1000×1000 확인"}</span></button><div><div className="flex items-start justify-between gap-3"><label className="flex gap-3"><input type="checkbox" checked={selected.includes(g.key)} onChange={()=>toggle(g.key)} disabled={g.truncated}/><span><b>{g.title}</b><span className="block text-xs text-zinc-500">{[g.groupName,g.albumName,g.versionName].filter(Boolean).join(" · ")} · {g.products.length}개 옵션</span><span className="block text-xs font-semibold text-violet-700">{g.ebayItemId?`등록됨 · 새 옵션 ${g.newOptionCount}개`:`신규 등록 · 완료 옵션 ${g.products.length}개`}</span><span className={`block text-xs font-semibold ${g.thumbnailStatus==="READY"?"text-emerald-700":g.thumbnailStatus==="FAILED"?"text-red-700":"text-amber-700"}`}>{g.thumbnailStatus==="READY"?`썸네일 준비 완료${g.thumbnailGeneratedAt?` · ${new Date(g.thumbnailGeneratedAt).toLocaleString("ko-KR")}`:""}`:g.thumbnailStatus==="FAILED"?`썸네일 실패 · ${g.thumbnailError??"다시 생성해 주세요."}`:"썸네일 생성 필요"}</span>{g.activeSingleCount>0&&<span className="block text-xs text-amber-700">기존 활성 단품 {g.activeSingleCount}개</span>}</span></label></div><div className="mt-3 flex gap-2 overflow-x-auto">{g.products.map(p=><div key={p.id} className="w-20 shrink-0"><div className="aspect-[2/3] overflow-hidden rounded bg-zinc-100">{p.imageUrl&&<img src={p.imageUrl} alt="" className="h-full w-full object-cover"/>}</div><p className="truncate text-[11px]">{p.variationName}</p><p className="text-[10px] text-zinc-500">${p.priceUsd??"-"}</p></div>)}</div></div></article>)}</div>
  </section>
  <div className="sticky bottom-4 space-y-3 rounded-xl border bg-white/95 p-4 shadow-lg backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{selected.length}개 묶음 선택</b><p className="text-xs text-zinc-500">썸네일 준비 {selectedGroups.filter(group=>group.thumbnailStatus==="READY").length}/{selectedGroups.length}</p></div><div className="flex flex-wrap gap-2"><button disabled={!selected.length||busy} onClick={prepareThumbnails} className="h-11 rounded border border-violet-300 px-4 text-sm font-semibold text-violet-700 disabled:text-zinc-300">{busy&&progress?`${progress.completed}/${progress.total} 썸네일 생성 중`:"선택 묶음 썸네일 만들기"}</button><button disabled={!selected.length||busy} onClick={()=>download("/api/listing-upload/variation-groups/end-singles","ebay-end-replaced-singles")} className="h-11 rounded border border-red-300 px-4 text-sm font-semibold text-red-700 disabled:text-zinc-300">기존 단품 종료 CSV</button><button disabled={!selectedReady||busy||!data.latestCompleteReportAt||!data.pricingReady} onClick={downloadVariationCsv} className="h-11 rounded bg-violet-600 px-5 text-sm font-semibold text-white disabled:bg-zinc-300">신규 등록·옵션 추가 CSV</button></div></div>{!selectedReady&&selected.length>0&&!busy&&<p className="rounded bg-amber-50 p-2 text-xs text-amber-800">현재 구성의 썸네일을 모두 준비해야 CSV를 받을 수 있습니다.</p>}{progress&&<div className="space-y-1"><div className="flex justify-between gap-3 text-xs text-zinc-600"><span className="truncate">{progress.completed<progress.total?`현재: ${progress.currentTitle}`:"썸네일 준비 완료"}</span><span className="shrink-0">경과 {formatDuration(elapsedSeconds)}</span></div><div className="h-2 overflow-hidden rounded-full bg-zinc-200"><div className="h-full bg-violet-600 transition-[width]" style={{width:`${progress.total?Math.max(3,progress.completed/progress.total*100):0}%`}}/></div><p className="text-[11px] text-zinc-500">각 묶음의 카드를 합성해 R2에 저장합니다. 이미 같은 구성으로 준비된 썸네일은 재사용합니다.</p></div>}{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div>
  {preview&&<div role="dialog" aria-modal="true" onClick={()=>setPreview(null)} className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-4"><div onClick={e=>e.stopPropagation()} className="max-h-full max-w-4xl overflow-auto rounded-xl bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><b>{preview.title}</b><p className="text-xs text-zinc-500">1000×1000 미리보기 · 아직 R2에 저장되지 않음</p></div><button onClick={()=>setPreview(null)} className="rounded bg-zinc-900 px-3 py-2 text-sm text-white">닫기</button></div><img src={preview.url} alt={`${preview.title} 썸네일 미리보기`} className="h-auto w-[min(1000px,90vw)]"/></div></div>}
 </div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-4"><p className="text-xs text-zinc-500">{label}</p><p className="text-xl font-bold">{value}</p></div>}
function formatDuration(seconds:number){const minutes=Math.floor(seconds/60);const rest=seconds%60;return minutes?`${minutes}분 ${String(rest).padStart(2,"0")}초`:`${rest}초`}
