ALTER TABLE "variation_thumbnail_settings"
  ADD COLUMN IF NOT EXISTS "image_exposure" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "image_contrast" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "image_saturation" DOUBLE PRECISION NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "background_enabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "background_url" TEXT,
  ADD COLUMN IF NOT EXISTS "background_key" TEXT,
  ADD COLUMN IF NOT EXISTS "background_padding" INTEGER NOT NULL DEFAULT 80;
